### ISSUE TITLE
build as docker-compose service

### ISSUE THREAD

**Issue by mdjaman** [BWITS/Docker-builder#6]
Hello, I don't know if im doing wrong but can't use `pdf2htmlex-alpine` as docker-compose service

Below docker-compose.yml

```
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: marketing-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
      - redis
      - pdf2html
    environment:
      - NODE_ENV=development
  mysql:
    image: mysql
    container_name: marketing-mysql
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    #restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: marketing
      MYSQL_DATABASE: marketing
      MYSQL_USER: marketing
      MYSQL_PASSWORD: marketing
  redis:
    image: redis
    container_name: marketing-redis
    volumes:
      - ./docker/redis:/var/lib/redis
    ports:
      - "63790:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb
  pdf2html:
    image: bwits/pdf2htmlex-alpine
    container_name: marketing-pdf2html
    volumes:
      - ./server/files/mails:/pdf
```
